{santiago, lima}.
{lima, bogota}.
{lima, mexico_city}.
{bogota, buenos_aires}.
{bogota, mexico_city}.
{bogota, sao_paulo}.
{buenos_aires, sao_paulo}.
{sao_paulo, lagos}.
{sao_paulo, madrid}.
{mexico_city, chicago}.
{mexico_city, los_angeles}.
{mexico_city, miami}.
{miami, atlanta}.
{miami, washington}.
{los_angeles, chicago}.
{los_angeles, san_francisco}.
{los_angeles, sydney}.
{lagos, khartoum}.
{lagos, kinshasa}.
{khartoum, cairo}.
{khartoum, johannesburg}.
{khartoum, kinshasa}.
{kinshasa, johannesburg}.
{san_francisco, chicago}.
{san_francisco, manila}.
{san_francisco, tokyo}.
{chicago, atlanta}.
{chicago, montreal}.
{atlanta, washington}.
{montreal, new_york}.
{montreal, washington}.
{washington, new_york}.
{new_york, london}.
{new_york, madrid}.
{london, essen}.
{london, paris}.
{london, madrid}.
{madrid, algiers}.
{madrid, paris}.
{paris, algiers}.
{paris, essen}.
{paris, milan}.
{essen, st_petersburg}.
{essen, milan}.
{milan, istanbul}.
{st_petersburg, istanbul}.
{st_petersburg, moscow}.
{algiers, cairo}.
{algiers, istanbul}.
{cairo, baghdad}.
{cairo, istanbul}.
{cairo, riyad}.
{istanbul, baghdad}.
{istanbul, moscow}.
{moscow, tehran}.
{baghdad, karachi}.
{baghdad, riyad}.
{baghdad, tehran}.
{riyad, karachi}.
{tehran, delhi}.
{tehran, karachi}.
{karachi, delhi}.
{karachi, mumbai}.
{delhi, chennai}.
{delhi, kolkata}.
{delhi, mumbai}.
{mumbai, kolkata}.
{mumbai, chennai}.
{chennai, bangkok}.
{chennai, jakarta}.
{chennai, kolkata}.
{kolkata, bangkok}.
{kolkata, hong_kong}.
{bangkok, ho_chi_mingh_city}.
{bangkok, hong_kong}.
{bangkok, jakarta}.
{jakarta, ho_chi_mingh_city}.
{jakarta, sydney}.
{beijing, seoul}.
{beijing, shangai}.
{shangai, hong_kong}.
{shangai, seoul}.
{shangai, taipei}.
{shangai, tokyo}.
{hong_kong, ho_chi_mingh_city}.
{hong_kong, manila}.
{hong_kong, taipei}.
{ho_chi_mingh_city, manila}.
{ho_chi_mingh_city, sydney}.
{seoul, tokyo}.
{taipei, manila}.
{taipei, osaka}.
{manila, sydney}.
{tokyo, osaka}.
