{santiago, insectoid}.
{lima, insectoid}.
{bogota, insectoid}.
{buenos_aires, insectoid}.
{sao_paulo, insectoid}.
{mexico_city, insectoid}.
{miami, insectoid}.
{los_angeles, insectoid}.
{lagos, insectoid}.
{khartoum, insectoid}.
{kinshasa, insectoid}.
{johannesburg, insectoid}.
{san_francisco, grey}.
{chicago, grey}.
{atlanta, grey}.
{montreal, grey}.
{washington, grey}.
{new_york, grey}.
{london, grey}.
{madrid, grey}.
{paris, grey}.
{essen, grey}.
{milan, grey}.
{st_petersburg, grey}.
{algiers, reptilian}.
{cairo, reptilian}.
{istanbul, reptilian}.
{moscow, reptilian}.
{baghdad, reptilian}.
{riyad, reptilian}.
{tehran, reptilian}.
{karachi, reptilian}.
{delhi, reptilian}.
{mumbai, reptilian}.
{chennai, reptilian}.
{kolkata, reptilian}.
{bangkok, martian}.
{jakarta, martian}.
{beijing, martian}.
{shangai, martian}.
{hong_kong, martian}.
{ho_chi_mingh_city, martian}.
{seoul, martian}.
{taipei, martian}.
{manila, martian}.
{sydney, martian}.
{tokyo, martian}.
{osaka, martian}.
